steps:
  # 1. Bangun (Build) Docker image
  - name: "gcr.io/cloud-builders/docker"
    # Tentukan secretEnv di sini dengan mapping LENGKAP
    secretEnv:
      - "SECRET_ABLY_KEY=projects/polar-city-473304-f4/secrets/ably-key/versions/latest"
    # Gunakan 'bash' sebagai entrypoint untuk mengizinkan substitusi variabel
    entrypoint: "bash"
    args:
      - "-c"
      - |
        docker build \
          -t "asia-southeast2-docker.pkg.dev/polar-city-473304-f4/chatku-repo/chatku-app:$COMMIT_SHA" \
          --build-arg "NEXT_PUBLIC_ABLY_KEY=$$SECRET_ABLY_KEY" \
          .
    # $$SECRET_ABLY_KEY diperlukan agar Cloud Build tahu untuk
    # menggunakan variabel $SECRET_ABLY_KEY, bukan mencoba substitusi Cloud Build

  # 2. Dorong (Push) Docker image ke Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "asia-southeast2-docker.pkg.dev/polar-city-473304-f4/chatku-repo/chatku-app:$COMMIT_SHA",
      ]

  # 3. Deploy ke Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk:slim"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "chatku-app"
      - "--image=asia-southeast2-docker.pkg.dev/polar-city-473304-f4/chatku-repo/chatku-app:$COMMIT_SHA"
      - "--region=asia-southeast2"
      - "--platform=managed"
      - "--allow-unauthenticated"
      - "--port=3000"
      # '--set-secrets' untuk runtime (ini sudah benar)
      - "--set-secrets=NEXT_PUBLIC_ABLY_KEY=ably-key:latest"
      - "--timeout=300"
      - "--max-instances=10"
      - "--memory=1Gi"
      - "--cpu=1"
      - "--min-instances=0"
      - "--cpu-boost"
      - "--no-cpu-throttling"

images:
  - "asia-southeast2-docker.pkg.dev/polar-city-473304-f4/chatku-repo/chatku-app:$COMMIT_SHA"

options:
  logging: CLOUD_LOGGING_ONLY

timeout: "2400s"

# Blok 'secrets:' di root tidak diperlukan untuk 'secretEnv' dan telah dihapus