steps:
  - name: "gcr.io/cloud-builders/docker"
    secretEnv:
      - "SECRET_ABLY_KEY"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        docker build \
          -t "asia-southeast2-docker.pkg.dev/polar-city-473304-f4/chatku-repo/chatku-app:$COMMIT_SHA" \
          --build-arg "NEXT_PUBLIC_ABLY_KEY=$$SECRET_ABLY_KEY" \
          .

  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "asia-southeast2-docker.pkg.dev/polar-city-473304-f4/chatku-repo/chatku-app:$COMMIT_SHA",
      ]

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk:slim"
    entrypoint: bash
    args:
      - "-c"
      - |
        gcloud run deploy chatku-app \
          --image=asia-southeast2-docker.pkg.dev/polar-city-473304-f4/chatku-repo/chatku-app:$COMMIT_SHA \
          --region=asia-southeast2 \
          --platform=managed \
          --allow-unauthenticated \
          --port=3000 \
          --set-secrets=NEXT_PUBLIC_ABLY_KEY=ably-key:latest \
          --timeout=300 \
          --max-instances=10 \
          --memory=1Gi \
          --cpu=1 \
          --min-instances=0 \
          --cpu-throttling \
          --no-use-http2 \
          --execution-environment=gen2 \
          --cpu-boost \
          --session-affinity
    timeout: "900s"

images:
  - "asia-southeast2-docker.pkg.dev/polar-city-473304-f4/chatku-repo/chatku-app:$COMMIT_SHA"

options:
  logging: CLOUD_LOGGING_ONLY

timeout: "2400s"

availableSecrets:
  secretManager:
    - versionName: projects/polar-city-473304-f4/secrets/ably-key/versions/latest
      env: "SECRET_ABLY_KEY"
