steps:
  # 1. Bangun (Build) Docker image
  - name: "gcr.io/cloud-builders/docker"
    # --- TAMBAHAN PENTING ---
    # Beri akses ke secret selama langkah build ini
    availableSecrets:
      secretManager:
        - versionName: projects/polar-city-473304-f4/secrets/ably-key/versions/latest
          env: "SECRET_ABLY_KEY" # Kita akan memetakannya ke ENV ini
    # --- AKHIR TAMBAHAN ---
    args:
      [
        "build",
        "-t",
        "asia-southeast2-docker.pkg.dev/polar-city-473304-f4/chatku-repo/chatku-app:$COMMIT_SHA",
        # --- TAMBAHAN PENTING ---
        # Teruskan secret ke dalam Dockerfile sebagai build-arg
        "--build-arg",
        "NEXT_PUBLIC_ABLY_KEY=$(cat /run/secrets/SECRET_ABLY_KEY)",
        # --- AKHIR TAMBAHAN ---
        ".",
      ]
    # Tentukan path ke secret
    secretEnv: ["SECRET_ABLY_KEY"]

  # 2. Dorong (Push) Docker image ke Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "asia-southeast2-docker.pkg.dev/polar-city-473304-f4/chatku-repo/chatku-app:$COMMIT_SHA",
      ]

  # 3. Deploy ke Cloud Run (Langkah ini sudah benar, tetap teruskan secret untuk runtime)
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk:slim"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "chatku-app"
      - "--image=asia-southeast2-docker.pkg.dev/polar-city-473304-f4/chatku-repo/chatku-app:$COMMIT_SHA"
      - "--region=asia-southeast2"
      - "--platform=managed"
      - "--allow-unauthenticated"
      - "--port=3000"
      - "--set-secrets=NEXT_PUBLIC_ABLY_KEY=ably-key:latest" # <-- Ini untuk runtime
      - "--timeout=300"
      - "--max-instances=10"
      - "--memory=1Gi"
      - "--cpu=1"
      - "--min-instances=0"
      - "--cpu-boost"
      - "--no-cpu-throttling"

images:
  - "asia-southeast2-docker.pkg.dev/polar-city-473304-f4/chatku-repo/chatku-app:$COMMIT_SHA"

options:
  logging: CLOUD_LOGGING_ONLY

timeout: "2400s"

# --- TAMBAHAN PENTING ---
# Definisikan secret yang akan digunakan oleh seluruh build
secrets:
  - secretManager:
      versionName: projects/polar-city-473304-f4/secrets/ably-key/versions/latest
      env: "SECRET_ABLY_KEY"